global.options = { };

describe('xTuple Installer', function () {
  var assert = require('chai').assert,
    exec = require('execSync').exec,
    _ = require('underscore'),
    path = require('path'),
    pgcli = require('../../lib/pg-cli'),
    pgPhase = require('../pg'),
    getOptions = function ($k) {
      return {
        quiet: true,
        xt: {
          edition: 'core',
          name: 'xt' + $k,
          setupdemos: true,
          adminpw: '123',
          build_common: { },
          build_main: { },
          database: { },
          serverconfig: { },
          testconfig: { },
          clone: { }
        },
        nginx: {
          domain: 'localhost',
          // mock; generated by nginx.ssl#beforeTask
          site: { },
          ssl: { }
        },
        pg: {
          version: process.env.XT_PG_VERSION,
          host: 'localhost',
          mode: 'test',
          snapshotcount: 7,
          cluster: { },
          snapshotmgr: { },
          tuner: { },
          hba: { },
          config: {
            slots: 1,
            shared_buffers: 128,
            temp_buffers: 8,
            max_connections: 8,
            work_mem: 1,
            maintenance_work_mem: 8,
            locale: 'en_US.UTF-8'
          }
        },
        sys: {
          service: { },
          cups: { },
          policy: { }
        }
      };
    };

  global.baseClusterInstallPlan = [
    {name: 'sys', tasks: [ 'policy' ]},
    {name: 'xt', tasks: [ 'clone', 'serverconfig' ]},
    {name: 'pg', tasks: [ 'config', 'cluster' ]},
    {name: 'nginx', tasks: [ 'ssl' ]},
    {name: 'pg', tasks: [ 'hba', 'tuner' ]},
    {name: 'xt', tasks: [ 'database' ]},
    {name: 'sys', tasks: [ 'etchosts' ]},
  ];

  global.baseAppInstallPlan = global.baseClusterInstallPlan.concat([
    {name: "xt", tasks: [ 'build_common', 'build_main' ] }
  ]);

  global.fullInstallPlan = global.baseAppInstallPlan.concat([
    {name: 'sys', tasks: [ 'cups', 'service' ]},
    {name: 'pg', tasks: [ 'snapshotmgr' ]}
  ]);

  beforeEach(function () {
    global.options = getOptions(
      Math.round((Math.random() * 2e16)).toString(36).replace(/[0-9]/g, '')
    );
  });

  it('must run with root privileges', function () {
    assert(
      exec('id -u').stdout.indexOf('0') === 0,
      'installer tests must be run with sudo'
    );
  });
  it('must set XT_PG_VERSION environment variable', function () {
    assert.include([ '9.1', '9.3' ], process.env.XT_PG_VERSION);
  });

  require('./sys');
  require('./pg');
  require('./nginx');
  require('./xt');
});
